# Generated by Django 4.0.1 on 2022-02-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_election_groups_question_option_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_ends_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='voting_starts_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
