# Generated by Django 4.0.1 on 2022-02-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_election_number_of_polls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='selection_type',
            field=models.CharField(choices=[('single', 'Single Select'), ('multiple', 'Multiple Select')], default='single_select', max_length=15),
        ),
    ]
