# Generated by Django 4.0.1 on 2022-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_option_order_alter_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_selections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_selections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
