# Generated by Django 4.0.1 on 2022-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_question_max_selections_question_min_selections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='election',
            name='manual_closing',
            field=models.BooleanField(default=True),
        ),
    ]
