# Generated by Django 4.0.1 on 2022-06-06 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_election_options_election_manual_closing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.option'),
        ),
    ]
