# Generated by Django 4.0.1 on 2022-06-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_closedvote_alter_submission_election_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClosedVote',
            new_name='ClosedElection',
        ),
    ]
